name: Update Submodule

on:
  repository_dispatch:
    types:
      - update-submodule

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Authorize Git
        run: |
          git config --global user.email "bot@noreply.github.com"
          git config --global user.name "Git Bot"
          
      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Commit changes
        run: |
          git add content
          git commit -m "Update content"
          git push origin v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
